# Generated by Django 5.2.18 on 2026-10-08 23:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('huespedes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('adicionales', models.ManyToManyField(blank=True, related_name='reservas', to='reservas.adicional')),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.PROTECT, to='habitaciones.habitacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
