# Generated by Django 5.2.18 on 2026-10-08 23:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
