# Generated by Django 5.2.18 on 2026-10-08 23:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva')),
            ],
        ),
    ]
